# src/pycfftables/_lib.pyi
from typing import Iterator

class CFF:
    @property
    def d(self) -> int: ...
    @d.setter
    def d(self, value: int) -> None: ...

    @property
    def t(self) -> int: ...

    @property
    def n(self) -> int: ...

    @property
    def shape(self) -> tuple[int, int]: ...

    @property
    def rows(self) -> RowsView: ...

    @property
    def cols(self) -> ColsView: ...

    @property
    def subsets(self) -> SubsetsView: ...

    @property
    def pools(self) -> PoolsView: ...

    def __getitem__(self, key: tuple[int, int]) -> int: ...
    def __setitem__(self, key: tuple[int, int], value: int) -> None: ...
    def verify(self) -> bool: ...
    def write_to_filepath(self, filepath: str) -> None: ...
    def copy(self) -> CFF: ...

    @staticmethod
    def all_zeros(d: int, t: int, n: int) -> CFF: ...

    @staticmethod
    def identity(d: int, n: int) -> CFF: ...

    @staticmethod
    def sperner(n: int) -> CFF: ...

    @staticmethod
    def sts(v: int) -> CFF: ...

    @staticmethod
    def reed_solomon(p: int, exp: int, k: int, m: int) -> CFF: ...

    @staticmethod
    def short_reed_solomon(p: int, exp: int, k: int, m: int, s: int) -> CFF: ...

    @staticmethod
    def porat_rothschild(p: int, exp: int, k: int, r: int, m: int) -> CFF: ...

    @staticmethod
    def extend_by_one(to_extend: CFF) -> CFF: ...

    @staticmethod
    def double(to_double: CFF) -> CFF: ...

    @staticmethod
    def add(left: CFF, right: CFF) -> CFF: ...

    @staticmethod
    def kronecker(left: CFF, right: CFF) -> CFF: ...

    @staticmethod
    def optimized_kronecker(outer: CFF, inner: CFF, bottom: CFF) -> CFF: ...

class ColsView:
    def __len__(self) -> int: ...
    def __getitem__(self, c: int) -> tuple[int, ...]: ...
    def __iter__(self) -> Iterator[tuple[int, ...]]: ...

class RowsView:
    def __len__(self) -> int: ...
    def __getitem__(self, r: int) -> tuple[int, ...]: ...
    def __iter__(self) -> Iterator[tuple[int, ...]]: ...

class PoolsView:
    def __len__(self) -> int: ...
    def __getitem__(self, r: int) -> tuple[int, ...]: ...
    def __iter__(self) -> Iterator[tuple[int, ...]]: ...

class SubsetsView:
    def __len__(self) -> int: ...
    def __getitem__(self, c: int) -> tuple[int, ...]: ...
    def __iter__(self) -> Iterator[tuple[int, ...]]: ...

class CFFTable:
    def __init__(self, d_max: int, t_max: int, n_max: int) -> None: ...

    @property
    def d_max(self) -> int: ...

    @property
    def t_max(self) -> int: ...

    @property
    def n_max(self) -> int: ...

    def get_by_t(self, d: int, t: int) -> CFF: ...
    def get_by_n(self, d: int, n: int) -> CFF: ...